services:
  alicdt-manager:
    image: ghcr.io/lillinlin/alicdt-manager:latest
    container_name: alicdt-manager
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
